# Generated by Django 4.0.4 on 2022-07-14 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=120, verbose_name='Apellido materno')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_carrera', models.CharField(max_length=50, verbose_name='Carrera')),
                ('nivel_estudios', models.CharField(choices=[('0', 'Bachillerato'), ('1', 'Licenciatura'), ('2', 'Maestria'), ('3', 'Doctorado'), ('4', 'Otro')], max_length=50, verbose_name='Nivel de estudios')),
                ('promedio', models.PositiveIntegerField(verbose_name='Promedio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_estudios', to='app1.persona')),
            ],
            options={
                'verbose_name': 'Estudios',
                'verbose_name_plural': 'Estudios',
                'ordering': ['id'],
            },
        ),
    ]
